# The advance features in Numpy
There are a lot of advanced features in numpy:
* Broadcasting
* ufunc usage
* structured and record array
This section we will briefly explore some of them.

## Broadcasting
__Broadcasting__ describes how arithmetic works between arrays of different shapes.

In [1]:
import numpy as np
arr = np.arange(6)
arr * 4

array([ 0,  4,  8, 12, 16, 20])

The scalar value __4__ has ben _broadcast_ to all of the other elments to all of the other elements in the example above.

In [2]:
arr = np.random.randn(5, 3)

In [3]:
zero_mean = arr.mean(0)

In [4]:
zero_mean.shape

(3,)

In [5]:
test = arr - zero_mean

In [6]:
test

array([[ 0.106022  ,  0.27164727, -0.76114162],
       [ 0.35445334, -0.42133455,  0.34628824],
       [ 0.05510637, -0.89005128, -1.25306941],
       [-0.37421091, -0.29796135,  1.62540707],
       [-0.14137079,  1.3376999 ,  0.04251571]])

From the example above, we can see an important the broadcasting rule: two arrays are compatible for __broadcasting__ if for each _trailing dimension_, the axis lengths match or if either of the lengths is 1. Broadcasting is then performed over the missing and / or length 1 dimensions. 

Thus, the trailing dimensions in __arr__ is 3 since the second dimension is empty, it matches so the broadcasting can be applied. Then we can test the previous example by reshap it.

In [7]:
zero_mean.reshape(3, 1)
test = arr - zero_mean
test

array([[ 0.106022  ,  0.27164727, -0.76114162],
       [ 0.35445334, -0.42133455,  0.34628824],
       [ 0.05510637, -0.89005128, -1.25306941],
       [-0.37421091, -0.29796135,  1.62540707],
       [-0.14137079,  1.3376999 ,  0.04251571]])

According to the __rule__ above, broadcasting over other axis should be caution.

In [8]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [10]:
arr - arr.mean(1).reshape(5,1)

array([[ 0.26844593,  0.40767158, -0.67611751],
       [ 0.29591747, -0.50627003,  0.21035256],
       [ 0.78571095, -0.18584631, -0.59986464],
       [-0.65735604, -0.60750609,  1.26486213],
       [-0.51971925,  0.93295182, -0.41323257]])

A common problem is needing to add a new axis with length 1 specifically for boardcasting purposes.

In [11]:
arr = np.random.randn(3, 4, 5)
deep_mean = arr.mean(2)
deep_mean

array([[ 0.56210033, -0.30190933, -0.0206805 ,  0.50941415],
       [ 0.14063325, -0.27912115, -0.29001508,  0.28827494],
       [ 0.61606837, -0.27201633,  0.18779557, -0.25129182]])

In [12]:
result = arr - deep_mean[:, :, np.newaxis]
result

array([[[ -2.46508264e-01,  -3.54272676e-01,   1.01019908e-01,
           5.42192616e-01,  -4.24315838e-02],
        [ -6.65518143e-01,  -4.15537905e-01,   1.11271465e+00,
          -1.17226507e+00,   1.14060646e+00],
        [ -4.66729847e-01,   4.42614262e-01,   8.08505370e-01,
           7.44809441e-02,  -8.58870730e-01],
        [  2.07778431e-03,   4.06737103e-01,  -7.69917597e-01,
           8.37557343e-01,  -4.76454633e-01]],

       [[  1.40095912e+00,  -1.05064059e+00,  -1.43505382e+00,
          -3.52671619e-01,   1.43740691e+00],
        [  6.02438728e-01,  -6.54356749e-01,   8.53725303e-01,
          -9.14455540e-01,   1.12648258e-01],
        [  3.39993962e-01,   1.71679167e+00,  -2.38189540e+00,
          -9.93251512e-02,   4.24434916e-01],
        [ -3.40242581e-01,  -4.70190950e-02,   2.59198919e-01,
           2.35064432e+00,  -2.22258157e+00]],

       [[ -5.78044319e-01,  -8.39925328e-01,  -8.61201405e-01,
           1.33357408e+00,   9.45596970e-01],
        [ -2.06

In [13]:
cols = np.array([3.49, -0.94, 5.92, 1.3])

In [14]:
test = np.zeros((4, 3))
test[:] = cols[:, np.newaxis]
test

array([[ 3.49,  3.49,  3.49],
       [-0.94, -0.94, -0.94],
       [ 5.92,  5.92,  5.92],
       [ 1.3 ,  1.3 ,  1.3 ]])

In [15]:
test[:2] = [[100.43],[-56.943]]
test

array([[ 100.43 ,  100.43 ,  100.43 ],
       [ -56.943,  -56.943,  -56.943],
       [   5.92 ,    5.92 ,    5.92 ],
       [   1.3  ,    1.3  ,    1.3  ]])

## ufunc instance methods
__ufunc__ provide a series of functions that can avoid writing loops.

In [16]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [17]:
arr = np.random.randn(5, 5)
arr[::2].sort(1)

In [18]:
arr[:,:-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [19]:
np.logical_and.reduce(arr[:,:-1] < arr[:, 1:], axis = 1)

array([ True, False,  True, False,  True], dtype=bool)

It is equivalent to __`np.where`__ with __`np.logical_and.redue`__. 

In [20]:
np.all(arr[:,:-1] < arr[:,1:], axis = 1)

array([ True, False,  True, False,  True], dtype=bool)

__`accumulate`__ is related to __`reduce`__ like __`cumsum`__ is related to __`sum`__, and produces the intermediate _accumulated_ values.

In [21]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

__`outer`__ performs a pairwise cross-product between two arrays. 

In [22]:
arr = np.random.randn(5)
result = np.multiply.outer(arr, np.arange(5))

In [23]:
result

array([[-0.        , -0.51155877, -1.02311753, -1.5346763 , -2.04623507],
       [ 0.        ,  0.25523709,  0.51047418,  0.76571127,  1.02094835],
       [-0.        , -1.00592493, -2.01184986, -3.01777478, -4.02369971],
       [ 0.        ,  0.2120256 ,  0.42405119,  0.63607679,  0.84810239],
       [-0.        , -0.01899536, -0.03799072, -0.05698608, -0.07598144]])

__`reduceat`__ performs a _local reduce_ to have a similar __groupby__ functionality. 

In [24]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

## Structured array and record array
As we know, numpy ndarry is a _homogeneous_ data container, a block of memory where each element takes up the same number of bytes determined by __dtype__. There is an advanced concept in numpy called _structured array_ or datatype that is an ndarray where each element can represent a _heterogeneous_ data similar a __struct__ in C.

In [25]:
 x = np.array([(1, 0.43, "This is"), (934, -5.1, "world")],
               dtype = [('ID', 'i4'), ('Measure', '>f4'),('Value', "|S10")])

In [27]:
x[1]

(934, -5.099999904632568, b'world')

From the example, one can conclude that the _structured array_ is defined through the __dtype__object. And the fields of a record can be specified with __four__ alternative ways.
* ### String argument
The structure expects a comma-seperated list of type specifiers, optionally with extra shape information.

In [28]:
x = np.zeros(2, dtype="2i4, 3f4, (4, 6)c8")
x

array([ ([0, 0], [0.0, 0.0, 0.0], [[0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j]]),
       ([0, 0], [0.0, 0.0, 0.0], [[0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j, 0j, 0j]])], 
      dtype=[('f0', '<i4', (2,)), ('f1', '<f4', (3,)), ('f2', '<c8', (4, 6))])

* ### Tuple argument
When a structure is mapped to an existing data type, pairing a tuple for the exisitng type with a matching dtype definition. 

In [33]:
x = np.ones(4, dtype = ('i4', [('r', 'u1'), ('g', 'u1'), ('b', 'u1'),('a', 'u1')]))
x

array([1, 1, 1, 1], dtype=int32)

* ### List Argument
A list of tuples can be applied. In each tuple, those elements can be found:
1. The name of field
2. The type of field
3. The shape as optional element

In [34]:
x = np.ones(5, dtype=[('type', 'f4'), ('age','i4'), ('value', 'f4', (2,4))])
x

array([(1.0, 1, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, 1, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, 1, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, 1, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, 1, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]])], 
      dtype=[('type', '<f4'), ('age', '<i4'), ('value', '<f4', (2, 4))])

In [35]:
x['value']

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]], dtype=float32)

* ### Dictionary Argument
There are two different forms:
* A dictionary consists of __names__ and __formats__ as required keys, each has an equal sized list of values.
* A dictionary consists of name keys with tuple values specifying type, offset and an optional title.

In [38]:
np.zeros(3, dtype={'names': ['first', 'last'], 'formats':['i4', 'f4']})

array([(0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[('first', '<i4'), ('last', '<f4')])

In [40]:
x = np.zeros(4, dtype={'first': ('i1', 0, 'title 1'), 'second': ('f4', 1, 'title 2')})

array([(0, 0.0), (0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[(('title 1', 'first'), 'i1'), (('title 2', 'second'), '<f4')])

## Accesing fields
One can access field names of dtype objects, and all other related information. With that information, one can access multiple fields by passing a list of field names as an index into the array itslef.

In [41]:
x.dtype.names

('type', 'age', 'value')

In [42]:
x.dtype.fields

mappingproxy({'age': (dtype('int32'), 4),
              'type': (dtype('float32'), 0),
              'value': (dtype(('<f4', (2, 4))), 8)})

In [46]:
x.dtype.fields['age'][1]

4

In [47]:
x[['type', 'value']]

array([(1.0, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]),
       (1.0, [[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]])], 
      dtype=[('type', '<f4'), ('value', '<f4', (2, 4))])

## Record Array
__Record Array__ allows one to acess fields of structured array by __attribute rather than by index__ using a subclass of ndarray called __`numpy.recarray`__.

In [48]:
x = np.rec.array([(1, 0.43, "This is"), (934, -5.1, "world")],
               dtype = [('ID', 'i4'), ('Measure', '>f4'),('Value', "|S10")])

In [49]:
x.ID

array([  1, 934], dtype=int32)

In [51]:
x.Measure

array([ 0.43000001, -5.0999999 ], dtype=float32)

## Sorting
Generally two ways to sort:
* In-place sorting without copying

In [52]:
arr = np.random.randn(10)

In [53]:
arr

array([ 0.38600244,  0.12959026,  0.37263553,  1.03226543, -0.08930729,
       -0.80374109,  0.87745527,  0.36021556,  0.54244687,  0.79475328])

In [54]:
arr.sort()

In [55]:
arr

array([-0.80374109, -0.08930729,  0.12959026,  0.36021556,  0.37263553,
        0.38600244,  0.54244687,  0.79475328,  0.87745527,  1.03226543])

* Sorting returns a copy

In [59]:
arr = np.random.randn(5)

In [60]:
arr

array([ 1.31644813,  0.48835484, -0.63618114, -1.08703501, -1.54148555])

In [61]:
np.sort(arr)

array([-1.54148555, -1.08703501, -0.63618114,  0.48835484,  1.31644813])

In [62]:
arr

array([ 1.31644813,  0.48835484, -0.63618114, -1.08703501, -1.54148555])

### Indirect sort
Sometimes one wants to reorder a 2D array by its first row, __`argsort`__ is the function to implement that.

In [63]:
values = np.array([5, 0, 3, 1, 2])
indexer = values.argsort()
indexer

array([1, 3, 4, 2, 0])

In [65]:
arr = np.random.randn(3, 5)
arr[0] = values
arr

array([[ 5.        ,  0.        ,  3.        ,  1.        ,  2.        ],
       [-1.64147515, -0.75559715, -0.47258772, -0.29489565, -1.43540243],
       [-1.3191719 ,  2.08978416, -0.10914456, -0.0887644 , -0.3223204 ]])

In [66]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.75559715, -0.29489565, -1.43540243, -0.47258772, -1.64147515],
       [ 2.08978416, -0.0887644 , -0.3223204 , -0.10914456, -1.3191719 ]])

__`lexsort`__ can perform an indirect _lexicographical_ sort on multiple key arrays.

In [69]:
first_name = np.array(['Bob', 'Shawn', 'Eric', 'Paul'])
last_name = np.array(['Jones', 'Arnold', 'Walters', 'Sethi'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

## Memory issue
When the dasta set is too large to fit into RAM, a _memory_mapped_ file can be used. Numpy implements a __memmap__ object that is ndarray-like enabling small segments of a large file to be read and written without reading the whole array into memory. 

## Performance Tips
* Convert loops to array operations and boolean array operations
* User broadcasting whenever possible
* Avoid copying data using array views
* Utilize ufuncs and ufuncs methods
If all methods above, use [Cython](http://cython.org)-- Python with static types and the ability to interleave functions implemented in C into Python-like code --  to get C-like performance. 

Furthermore, use C-ordering as an array's memory layout, since it is _contiguous_. 

In [70]:
arr_c = np.ones((100, 100),  order='C')
arr_f = np.ones((100, 100),  order='F')

In [71]:
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [72]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [73]:
%timeit arr_c.sum(1)

The slowest run took 25.58 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.77 µs per loop


In [74]:
%timeit arr_f.sum(1)

The slowest run took 17.92 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.23 µs per loop
